### ISSUE TITLE
Results of the app

### ISSUE THREAD

**Issue by arieldiaz90** [inlined/alone-together#3]
i follow the steps, but when i tried to see the friendship appear this 

a mapamundi with 

people are less famous than their friends.
people are more famous than their friends.
of people are more famous than their friends.

i can see the numbers.

https://paradox-b346f.firebaseapp.com/

**Comment by inlined** [comment]
It looks like the Twitter login isn't correctly set up. There's an error printed into the JS console that says: "Unable to determine the authorization endpoint for the specified provider. This may be an issue in the provider configuration."

To use the demo you'll need to set up your own twitter app and set up that app to be a login provider for Firebase auth at https://console.firebase.google.com
